//! Bambu Lab firmware dialect for G-code generation.
//!
//! Bambu Lab printers have extensive built-in start sequences for calibration,
//! purging, and bed leveling. The G-code start sequence is therefore simpler
//! than other dialects, as the printer handles many steps automatically.

use crate::commands::GcodeCommand;
use crate::dialect::{EndConfig, StartConfig};

/// Generate Bambu Lab-compatible start G-code sequence.
///
/// Bambu printers handle calibration and purging internally, so the
/// start sequence is minimal compared to other dialects.
pub fn start_gcode(config: &StartConfig) -> Vec<GcodeCommand> {
    vec![
        GcodeCommand::Comment("Generated by slicecore - Bambu Lab dialect".to_string()),
        GcodeCommand::Comment(
            "Note: Bambu printers have built-in calibration sequences".to_string(),
        ),
        GcodeCommand::SetRelativeExtrusion,
        GcodeCommand::SetBedTemp {
            temp: config.bed_temp,
            wait: false,
        },
        GcodeCommand::SetExtruderTemp {
            temp: config.nozzle_temp,
            wait: false,
        },
        GcodeCommand::Home {
            x: false,
            y: false,
            z: false,
        },
        GcodeCommand::SetBedTemp {
            temp: config.bed_temp,
            wait: true,
        },
        GcodeCommand::SetExtruderTemp {
            temp: config.nozzle_temp,
            wait: true,
        },
        // AMS (Automatic Material System) filament slot commands.
        // M620 S{slot} selects the AMS filament slot before loading.
        // M621 S{slot} confirms the filament is loaded from AMS.
        // Full AMS support requires 3MF format with filament mapping.
        GcodeCommand::Comment("AMS: M620 S0 / M621 S0 for filament slot selection".to_string()),
        GcodeCommand::Raw("M620 S0".to_string()),
        GcodeCommand::Raw("M621 S0".to_string()),
        GcodeCommand::ResetExtruder,
    ]
}

/// Generate Bambu Lab-compatible end G-code sequence.
///
/// Standard shutdown sequence with temperature off, fan off, and home.
pub fn end_gcode(config: &EndConfig) -> Vec<GcodeCommand> {
    vec![
        GcodeCommand::Comment("End G-code - Bambu Lab".to_string()),
        GcodeCommand::SetRelativePositioning,
        GcodeCommand::Retract {
            distance: config.retract_distance,
            feedrate: 2700.0,
        },
        GcodeCommand::SetAbsolutePositioning,
        GcodeCommand::SetExtruderTemp {
            temp: 0.0,
            wait: false,
        },
        GcodeCommand::SetBedTemp {
            temp: 0.0,
            wait: false,
        },
        GcodeCommand::FanOff,
        GcodeCommand::Home {
            x: true,
            y: true,
            z: false,
        },
        GcodeCommand::Raw("M84".to_string()),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn start_gcode_is_minimal() {
        let config = StartConfig {
            bed_temp: 60.0,
            nozzle_temp: 200.0,
            bed_x: 256.0,
            bed_y: 256.0,
        };
        let cmds = start_gcode(&config);
        let text: Vec<String> = cmds.iter().map(|c| c.to_string()).collect();
        let joined = text.join("\n");

        assert!(joined.contains("M83"), "should set relative extrusion");
        assert!(joined.contains("G28"), "should home");
        assert!(
            joined.contains("built-in calibration"),
            "should note built-in sequences"
        );
    }

    #[test]
    fn start_gcode_contains_ams_commands() {
        let config = StartConfig {
            bed_temp: 60.0,
            nozzle_temp: 200.0,
            bed_x: 256.0,
            bed_y: 256.0,
        };
        let cmds = start_gcode(&config);
        let text: Vec<String> = cmds.iter().map(|c| c.to_string()).collect();
        let joined = text.join("\n");

        assert!(
            joined.contains("M620"),
            "should contain M620 AMS select command"
        );
        assert!(
            joined.contains("M621"),
            "should contain M621 AMS confirm command"
        );
    }

    #[test]
    fn end_gcode_shuts_down_properly() {
        let config = EndConfig {
            retract_distance: 5.0,
        };
        let cmds = end_gcode(&config);
        let text: Vec<String> = cmds.iter().map(|c| c.to_string()).collect();
        let joined = text.join("\n");

        assert!(joined.contains("M104 S0"), "should turn off extruder");
        assert!(joined.contains("M140 S0"), "should turn off bed");
        assert!(joined.contains("M107"), "should turn off fan");
    }

    #[test]
    fn bambu_differs_from_marlin() {
        let start_config = StartConfig {
            bed_temp: 60.0,
            nozzle_temp: 200.0,
            bed_x: 256.0,
            bed_y: 256.0,
        };

        let bambu_start: Vec<String> = start_gcode(&start_config)
            .iter()
            .map(|c| c.to_string())
            .collect();
        let marlin_start: Vec<String> = crate::marlin::start_gcode(&start_config)
            .iter()
            .map(|c| c.to_string())
            .collect();

        assert_ne!(
            bambu_start, marlin_start,
            "Bambu and Marlin start should differ"
        );
    }
}
