//! Klipper firmware dialect for G-code generation.
//!
//! Klipper supports standard G-code commands but also provides extended
//! commands like `BED_MESH_CALIBRATE` and `TURN_OFF_HEATERS`. Standard
//! M104/M109/M140/M190 commands are fully supported.

use crate::commands::GcodeCommand;
use crate::dialect::{EndConfig, StartConfig};

/// Generate Klipper-compatible start G-code sequence.
///
/// The sequence includes Klipper-specific commands like `BED_MESH_CALIBRATE`
/// for automatic bed mesh leveling.
pub fn start_gcode(config: &StartConfig) -> Vec<GcodeCommand> {
    vec![
        GcodeCommand::Comment("Generated by slicecore - Klipper dialect".to_string()),
        GcodeCommand::SetRelativeExtrusion,
        GcodeCommand::SetBedTemp {
            temp: config.bed_temp,
            wait: false,
        },
        GcodeCommand::SetExtruderTemp {
            temp: config.nozzle_temp,
            wait: false,
        },
        GcodeCommand::SetBedTemp {
            temp: config.bed_temp,
            wait: true,
        },
        GcodeCommand::SetExtruderTemp {
            temp: config.nozzle_temp,
            wait: true,
        },
        GcodeCommand::Home {
            x: false,
            y: false,
            z: false,
        },
        GcodeCommand::Raw("BED_MESH_CALIBRATE".to_string()),
        GcodeCommand::ResetExtruder,
    ]
}

/// Generate Klipper-compatible end G-code sequence.
///
/// Uses Klipper's `TURN_OFF_HEATERS` extended command for clean shutdown.
pub fn end_gcode(config: &EndConfig) -> Vec<GcodeCommand> {
    vec![
        GcodeCommand::Comment("End G-code - Klipper".to_string()),
        GcodeCommand::SetRelativePositioning,
        GcodeCommand::Retract {
            distance: config.retract_distance,
            feedrate: 2700.0,
        },
        GcodeCommand::SetAbsolutePositioning,
        GcodeCommand::Raw("TURN_OFF_HEATERS".to_string()),
        GcodeCommand::FanOff,
        GcodeCommand::Home {
            x: true,
            y: true,
            z: false,
        },
        GcodeCommand::Raw("M84".to_string()),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn start_gcode_contains_klipper_commands() {
        let config = StartConfig {
            bed_temp: 60.0,
            nozzle_temp: 200.0,
            bed_x: 220.0,
            bed_y: 220.0,
        };
        let cmds = start_gcode(&config);
        let text: Vec<String> = cmds.iter().map(|c| c.to_string()).collect();
        let joined = text.join("\n");

        assert!(joined.contains("M83"), "should contain M83");
        assert!(
            joined.contains("BED_MESH_CALIBRATE"),
            "should contain Klipper mesh calibrate"
        );
        assert!(joined.contains("G28"), "should contain G28");
    }

    #[test]
    fn end_gcode_uses_turn_off_heaters() {
        let config = EndConfig {
            retract_distance: 5.0,
        };
        let cmds = end_gcode(&config);
        let text: Vec<String> = cmds.iter().map(|c| c.to_string()).collect();
        let joined = text.join("\n");

        assert!(
            joined.contains("TURN_OFF_HEATERS"),
            "should use Klipper TURN_OFF_HEATERS"
        );
        assert!(joined.contains("M107"), "should turn off fan");
    }

    #[test]
    fn klipper_differs_from_marlin() {
        let start_config = StartConfig {
            bed_temp: 60.0,
            nozzle_temp: 200.0,
            bed_x: 220.0,
            bed_y: 220.0,
        };
        let end_config = EndConfig {
            retract_distance: 5.0,
        };

        let klipper_start: Vec<String> = start_gcode(&start_config)
            .iter()
            .map(|c| c.to_string())
            .collect();
        let klipper_end: Vec<String> = end_gcode(&end_config)
            .iter()
            .map(|c| c.to_string())
            .collect();
        let marlin_start: Vec<String> = crate::marlin::start_gcode(&start_config)
            .iter()
            .map(|c| c.to_string())
            .collect();
        let marlin_end: Vec<String> = crate::marlin::end_gcode(&end_config)
            .iter()
            .map(|c| c.to_string())
            .collect();

        assert_ne!(
            klipper_start, marlin_start,
            "Klipper and Marlin start should differ"
        );
        assert_ne!(
            klipper_end, marlin_end,
            "Klipper and Marlin end should differ"
        );
    }
}
