//! Marlin firmware dialect for G-code generation.
//!
//! Marlin is the most widely used firmware for FDM 3D printers. This module
//! generates Marlin-compatible start and end G-code sequences.

use crate::commands::GcodeCommand;
use crate::dialect::{EndConfig, StartConfig};

/// Generate Marlin-compatible start G-code sequence.
///
/// The sequence:
/// 1. Sets relative extrusion mode (M83)
/// 2. Starts heating bed and nozzle simultaneously (no wait)
/// 3. Waits for bed temperature, then nozzle temperature
/// 4. Homes all axes
/// 5. Resets extruder position
pub fn start_gcode(config: &StartConfig) -> Vec<GcodeCommand> {
    vec![
        GcodeCommand::Comment("Generated by slicecore - Marlin dialect".to_string()),
        GcodeCommand::SetRelativeExtrusion,
        GcodeCommand::SetBedTemp {
            temp: config.bed_temp,
            wait: false,
        },
        GcodeCommand::SetExtruderTemp {
            temp: config.nozzle_temp,
            wait: false,
        },
        GcodeCommand::SetBedTemp {
            temp: config.bed_temp,
            wait: true,
        },
        GcodeCommand::SetExtruderTemp {
            temp: config.nozzle_temp,
            wait: true,
        },
        GcodeCommand::Home {
            x: false,
            y: false,
            z: false,
        },
        GcodeCommand::ResetExtruder,
    ]
}

/// Generate Marlin-compatible end G-code sequence.
///
/// The sequence:
/// 1. Switches to relative positioning for safe retract
/// 2. Retracts filament
/// 3. Returns to absolute positioning
/// 4. Turns off extruder, bed, and fan
/// 5. Homes X and Y (leaving Z in place)
/// 6. Disables stepper motors
pub fn end_gcode(config: &EndConfig) -> Vec<GcodeCommand> {
    vec![
        GcodeCommand::Comment("End G-code - Marlin".to_string()),
        GcodeCommand::SetRelativePositioning,
        GcodeCommand::Retract {
            distance: config.retract_distance,
            feedrate: 2700.0,
        },
        GcodeCommand::SetAbsolutePositioning,
        GcodeCommand::SetExtruderTemp {
            temp: 0.0,
            wait: false,
        },
        GcodeCommand::SetBedTemp {
            temp: 0.0,
            wait: false,
        },
        GcodeCommand::FanOff,
        GcodeCommand::Home {
            x: true,
            y: true,
            z: false,
        },
        GcodeCommand::Raw("M84".to_string()),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn start_gcode_contains_required_commands() {
        let config = StartConfig {
            bed_temp: 60.0,
            nozzle_temp: 200.0,
            bed_x: 220.0,
            bed_y: 220.0,
        };
        let cmds = start_gcode(&config);
        let text: Vec<String> = cmds.iter().map(|c| c.to_string()).collect();
        let joined = text.join("\n");

        assert!(joined.contains("M83"), "should contain M83 (relative extrusion)");
        assert!(joined.contains("M140 S60"), "should contain M140 (set bed temp)");
        assert!(joined.contains("M104 S200"), "should contain M104 (set extruder temp)");
        assert!(joined.contains("M190 S60"), "should contain M190 (wait bed temp)");
        assert!(joined.contains("M109 S200"), "should contain M109 (wait extruder temp)");
        assert!(joined.contains("G28"), "should contain G28 (home)");
        assert!(joined.contains("G92 E0"), "should contain G92 E0 (reset extruder)");
    }

    #[test]
    fn end_gcode_contains_required_commands() {
        let config = EndConfig {
            retract_distance: 5.0,
        };
        let cmds = end_gcode(&config);
        let text: Vec<String> = cmds.iter().map(|c| c.to_string()).collect();
        let joined = text.join("\n");

        assert!(joined.contains("M104 S0"), "should turn off extruder");
        assert!(joined.contains("M140 S0"), "should turn off bed");
        assert!(joined.contains("M107"), "should turn off fan");
    }

    #[test]
    fn full_round_trip_is_valid_text() {
        let start_config = StartConfig {
            bed_temp: 60.0,
            nozzle_temp: 200.0,
            bed_x: 220.0,
            bed_y: 220.0,
        };
        let end_config = EndConfig {
            retract_distance: 5.0,
        };

        let mut all_cmds = start_gcode(&start_config);
        all_cmds.push(GcodeCommand::LinearMove {
            x: Some(100.0),
            y: Some(100.0),
            z: Some(0.3),
            e: Some(0.5),
            f: Some(1800.0),
        });
        all_cmds.extend(end_gcode(&end_config));

        let output: String = all_cmds
            .iter()
            .map(|c| c.to_string())
            .collect::<Vec<_>>()
            .join("\n");

        // Should be valid UTF-8 text with no empty lines in commands
        assert!(!output.is_empty());
        for line in output.lines() {
            assert!(
                line.starts_with(';')
                    || line.starts_with('G')
                    || line.starts_with('M')
                    || line.starts_with('T'),
                "unexpected line prefix: {line}"
            );
        }
    }

    #[test]
    fn start_sequence_order_is_correct() {
        let config = StartConfig {
            bed_temp: 60.0,
            nozzle_temp: 200.0,
            bed_x: 220.0,
            bed_y: 220.0,
        };
        let cmds = start_gcode(&config);
        let text: Vec<String> = cmds.iter().map(|c| c.to_string()).collect();

        // M83 should come before temperature commands
        let m83_pos = text.iter().position(|l| l == "M83").unwrap();
        let m140_pos = text.iter().position(|l| l == "M140 S60").unwrap();
        assert!(m83_pos < m140_pos, "M83 should come before M140");

        // Home should come after waiting for temps
        let m109_pos = text.iter().position(|l| l == "M109 S200").unwrap();
        let g28_pos = text.iter().position(|l| l == "G28").unwrap();
        assert!(m109_pos < g28_pos, "M109 should come before G28");
    }
}
