//! RepRapFirmware dialect for G-code generation.
//!
//! RepRapFirmware (RRF3+, Duet boards) supports standard G-code and has
//! some firmware-specific commands. It defaults to relative extrusion but
//! we set M83 explicitly for clarity.

use crate::commands::GcodeCommand;
use crate::dialect::{EndConfig, StartConfig};

/// Generate RepRapFirmware-compatible start G-code sequence.
///
/// RepRapFirmware defaults to relative extrusion but M83 is set explicitly
/// for clarity. Temperature commands use standard M-codes.
pub fn start_gcode(config: &StartConfig) -> Vec<GcodeCommand> {
    vec![
        GcodeCommand::Comment("Generated by slicecore - RepRapFirmware dialect".to_string()),
        GcodeCommand::SetRelativeExtrusion,
        GcodeCommand::Home {
            x: false,
            y: false,
            z: false,
        },
        GcodeCommand::SetBedTemp {
            temp: config.bed_temp,
            wait: true,
        },
        GcodeCommand::SetExtruderTemp {
            temp: config.nozzle_temp,
            wait: true,
        },
        GcodeCommand::ResetExtruder,
    ]
}

/// Generate RepRapFirmware-compatible end G-code sequence.
///
/// Uses standard M-codes for temperature shutdown and stepper disable.
pub fn end_gcode(config: &EndConfig) -> Vec<GcodeCommand> {
    vec![
        GcodeCommand::Comment("End G-code - RepRapFirmware".to_string()),
        GcodeCommand::SetRelativePositioning,
        GcodeCommand::Retract {
            distance: config.retract_distance,
            feedrate: 2700.0,
        },
        GcodeCommand::SetAbsolutePositioning,
        GcodeCommand::SetExtruderTemp {
            temp: 0.0,
            wait: false,
        },
        GcodeCommand::SetBedTemp {
            temp: 0.0,
            wait: false,
        },
        GcodeCommand::FanOff,
        GcodeCommand::Home {
            x: true,
            y: true,
            z: false,
        },
        GcodeCommand::Raw("M0 H1".to_string()),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn start_gcode_homes_before_heating() {
        let config = StartConfig {
            bed_temp: 60.0,
            nozzle_temp: 200.0,
            bed_x: 220.0,
            bed_y: 220.0,
        };
        let cmds = start_gcode(&config);
        let text: Vec<String> = cmds.iter().map(|c| c.to_string()).collect();

        let g28_pos = text.iter().position(|l| l == "G28").unwrap();
        let m190_pos = text.iter().position(|l| l == "M190 S60").unwrap();
        assert!(g28_pos < m190_pos, "RepRap homes before waiting for temps");
    }

    #[test]
    fn end_gcode_contains_halt_command() {
        let config = EndConfig {
            retract_distance: 5.0,
        };
        let cmds = end_gcode(&config);
        let text: Vec<String> = cmds.iter().map(|c| c.to_string()).collect();
        let joined = text.join("\n");

        assert!(
            joined.contains("M0 H1"),
            "should contain RepRap halt command"
        );
    }

    #[test]
    fn reprap_differs_from_marlin() {
        let start_config = StartConfig {
            bed_temp: 60.0,
            nozzle_temp: 200.0,
            bed_x: 220.0,
            bed_y: 220.0,
        };
        let end_config = EndConfig {
            retract_distance: 5.0,
        };

        let reprap_start: Vec<String> = start_gcode(&start_config)
            .iter()
            .map(|c| c.to_string())
            .collect();
        let reprap_end: Vec<String> = end_gcode(&end_config)
            .iter()
            .map(|c| c.to_string())
            .collect();
        let marlin_start: Vec<String> = crate::marlin::start_gcode(&start_config)
            .iter()
            .map(|c| c.to_string())
            .collect();
        let marlin_end: Vec<String> = crate::marlin::end_gcode(&end_config)
            .iter()
            .map(|c| c.to_string())
            .collect();

        assert_ne!(
            reprap_start, marlin_start,
            "RepRap and Marlin start should differ"
        );
        assert_ne!(
            reprap_end, marlin_end,
            "RepRap and Marlin end should differ"
        );
    }
}
