//! Slicer auto-detection from G-code header comment patterns.
//!
//! Scans the first N lines of a G-code file to identify which slicer
//! generated it. Supports BambuStudio, OrcaSlicer, PrusaSlicer, and
//! Slicecore. Also determines the feature annotation format used by
//! each slicer.

use serde::{Deserialize, Serialize};

/// Known slicer types that can be auto-detected from G-code headers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SlicerType {
    /// BambuStudio slicer.
    BambuStudio,
    /// OrcaSlicer (BambuStudio fork).
    OrcaSlicer,
    /// PrusaSlicer.
    PrusaSlicer,
    /// Slicecore (this project's output).
    Slicecore,
    /// Unknown or unrecognized slicer.
    Unknown,
}

impl std::fmt::Display for SlicerType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SlicerType::BambuStudio => write!(f, "BambuStudio"),
            SlicerType::OrcaSlicer => write!(f, "OrcaSlicer"),
            SlicerType::PrusaSlicer => write!(f, "PrusaSlicer"),
            SlicerType::Slicecore => write!(f, "Slicecore"),
            SlicerType::Unknown => write!(f, "Unknown"),
        }
    }
}

/// Feature annotation comment format used by different slicers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum FeatureFormat {
    /// BambuStudio format: `; FEATURE: Outer wall`
    BambuFeature,
    /// PrusaSlicer format: `;TYPE:External perimeter`
    PrusaType,
    /// Try both formats (for unknown slicers).
    Both,
}

/// Maximum number of lines to scan for slicer identification.
const MAX_DETECT_LINES: usize = 100;

/// Detect the slicer that generated a G-code file by scanning header comments.
///
/// Examines up to 100 lines looking for slicer identification patterns in
/// comment lines. Priority order: BambuStudio > OrcaSlicer > PrusaSlicer >
/// Slicecore > Unknown (first match wins).
pub fn detect_slicer(lines: &[&str]) -> SlicerType {
    let limit = lines.len().min(MAX_DETECT_LINES);
    for line in &lines[..limit] {
        let trimmed = line.trim();
        // Only look at comment lines.
        if !trimmed.starts_with(';') {
            continue;
        }
        let lower = trimmed.to_lowercase();

        // Check in priority order: BambuStudio > OrcaSlicer > PrusaSlicer > Slicecore
        if lower.contains("bambustudio") {
            return SlicerType::BambuStudio;
        }
        if lower.contains("orcaslicer") || lower.contains("orca slicer") {
            return SlicerType::OrcaSlicer;
        }
        if lower.contains("prusaslicer") || lower.contains("prusa slicer") {
            return SlicerType::PrusaSlicer;
        }
        if lower.contains("slicecore") {
            return SlicerType::Slicecore;
        }
    }
    SlicerType::Unknown
}

/// Determine the feature annotation format for a given slicer type.
///
/// BambuStudio uses `; FEATURE:` prefix, PrusaSlicer uses `;TYPE:` prefix.
/// OrcaSlicer can use either (supports both). Unknown slicers try both.
pub fn detect_feature_format(slicer: SlicerType) -> FeatureFormat {
    match slicer {
        SlicerType::BambuStudio => FeatureFormat::BambuFeature,
        SlicerType::OrcaSlicer => FeatureFormat::Both,
        SlicerType::PrusaSlicer => FeatureFormat::PrusaType,
        SlicerType::Slicecore => FeatureFormat::PrusaType,
        SlicerType::Unknown => FeatureFormat::Both,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detect_bambustudio() {
        let lines = vec![
            "; HEADER_BLOCK_START",
            "; BambuStudio 02.05.00.66",
            "; model printing time: 9m 48s",
            "; HEADER_BLOCK_END",
        ];
        assert_eq!(detect_slicer(&lines), SlicerType::BambuStudio);
    }

    #[test]
    fn detect_orcaslicer() {
        let lines = vec![
            "; generated by OrcaSlicer 2.2.0",
            "; some other comment",
        ];
        assert_eq!(detect_slicer(&lines), SlicerType::OrcaSlicer);
    }

    #[test]
    fn detect_orcaslicer_with_space() {
        let lines = vec!["; generated by Orca Slicer 2.1.0"];
        assert_eq!(detect_slicer(&lines), SlicerType::OrcaSlicer);
    }

    #[test]
    fn detect_prusaslicer() {
        let lines = vec![
            "; generated by PrusaSlicer 2.8.0+linux-x86_64",
            "; some config",
        ];
        assert_eq!(detect_slicer(&lines), SlicerType::PrusaSlicer);
    }

    #[test]
    fn detect_prusaslicer_with_space() {
        let lines = vec!["; generated by Prusa Slicer 2.7.0"];
        assert_eq!(detect_slicer(&lines), SlicerType::PrusaSlicer);
    }

    #[test]
    fn detect_slicecore() {
        let lines = vec![
            "; Generated by slicecore v0.1.0",
            "; Marlin dialect",
        ];
        assert_eq!(detect_slicer(&lines), SlicerType::Slicecore);
    }

    #[test]
    fn detect_unknown_slicer() {
        let lines = vec![
            "; some random comment",
            "G28",
            "G90",
            "M82",
        ];
        assert_eq!(detect_slicer(&lines), SlicerType::Unknown);
    }

    #[test]
    fn detect_empty_input() {
        let lines: Vec<&str> = vec![];
        assert_eq!(detect_slicer(&lines), SlicerType::Unknown);
    }

    #[test]
    fn detect_ignores_non_comment_lines() {
        let lines = vec![
            "G28",
            "G90",
            "M82",
            "; BambuStudio 02.05.00.66",
        ];
        // Should still find it in comment line
        assert_eq!(detect_slicer(&lines), SlicerType::BambuStudio);
    }

    #[test]
    fn detect_bambustudio_priority_over_orcaslicer() {
        // If somehow both appear, BambuStudio should win (first match)
        let lines = vec![
            "; BambuStudio 02.05.00.66",
            "; generated by OrcaSlicer 2.2.0",
        ];
        assert_eq!(detect_slicer(&lines), SlicerType::BambuStudio);
    }

    #[test]
    fn feature_format_bambustudio() {
        assert_eq!(
            detect_feature_format(SlicerType::BambuStudio),
            FeatureFormat::BambuFeature
        );
    }

    #[test]
    fn feature_format_prusaslicer() {
        assert_eq!(
            detect_feature_format(SlicerType::PrusaSlicer),
            FeatureFormat::PrusaType
        );
    }

    #[test]
    fn feature_format_orcaslicer_both() {
        assert_eq!(
            detect_feature_format(SlicerType::OrcaSlicer),
            FeatureFormat::Both
        );
    }

    #[test]
    fn feature_format_unknown_both() {
        assert_eq!(
            detect_feature_format(SlicerType::Unknown),
            FeatureFormat::Both
        );
    }

    #[test]
    fn feature_format_slicecore() {
        assert_eq!(
            detect_feature_format(SlicerType::Slicecore),
            FeatureFormat::PrusaType
        );
    }

    #[test]
    fn slicer_type_display() {
        assert_eq!(format!("{}", SlicerType::BambuStudio), "BambuStudio");
        assert_eq!(format!("{}", SlicerType::OrcaSlicer), "OrcaSlicer");
        assert_eq!(format!("{}", SlicerType::PrusaSlicer), "PrusaSlicer");
        assert_eq!(format!("{}", SlicerType::Slicecore), "Slicecore");
        assert_eq!(format!("{}", SlicerType::Unknown), "Unknown");
    }
}
