//! Integration tests for G-code analysis covering all Phase 21 success criteria (SC1-SC7).
//!
//! Tests use synthetic G-code generated in memory (no external files required)
//! for CI-safe execution. Real G-code tests are gated with `#[ignore]`.

/// Generate a minimal BambuStudio-style G-code with:
/// - Header block with HEADER_BLOCK_START/END
/// - Slicer identification line
/// - Estimated time, filament length/volume/weight in header
/// - M83 relative extrusion mode
/// - Two layers with CHANGE_LAYER / Z_HEIGHT annotations
/// - FEATURE annotations (Outer wall, Inner wall, Sparse infill)
/// - G0/G1 moves with X/Y/Z/E/F parameters
/// - Retraction (negative E in relative mode)
/// - G92 E0 reset
fn synthetic_gcode_bambu_style() -> String {
    format!(
        r#"; HEADER_BLOCK_START
; BambuStudio 02.05.00.66
; model printing time: 1m 30s
; total layer number: 2
; total filament length [mm] : 100.00
; total filament volume [cm^3] : 0.24
; total filament weight [g] : 0.30
; filament_density: 1.24
; filament_diameter: 1.75
; HEADER_BLOCK_END

G90
M83
G28
M104 S200
M190 S60
G92 E0

; CHANGE_LAYER
; Z_HEIGHT: 0.2
; LAYER_HEIGHT: 0.2
; layer num/total_layer_count: 1/2
; FEATURE: Outer wall
G1 Z0.2 F600
G1 X10 Y0 E0.5 F1200
G1 X10 Y10 E0.5 F1200
G1 X0 Y10 E0.5 F1200
G1 X0 Y0 E0.5 F1200
; FEATURE: Sparse infill
G1 X2 Y2 E0.3 F1800
G1 X8 Y2 E0.3 F1800
G1 X8 Y8 E0.3 F1800
G1 X2 Y8 E0.3 F1800
G1 E-0.8 F2400
G0 X0 Y0 F9000

; CHANGE_LAYER
; Z_HEIGHT: 0.4
; LAYER_HEIGHT: 0.2
; layer num/total_layer_count: 2/2
; FEATURE: Outer wall
G1 Z0.4 F600
G1 X10 Y0 E0.5 F1200
G1 X10 Y10 E0.5 F1200
G1 X0 Y10 E0.5 F1200
G1 X0 Y0 E0.5 F1200
; FEATURE: Inner wall
G1 X1 Y1 E0.4 F1500
G1 X9 Y1 E0.4 F1500
G1 X9 Y9 E0.4 F1500
G1 X1 Y9 E0.4 F1500

G1 E-0.8 F2400
M84
"#
    )
}

/// Generate a PrusaSlicer-style G-code with `;TYPE:` format annotations.
fn synthetic_gcode_prusaslicer_style() -> String {
    format!(
        r#"; generated by PrusaSlicer 2.8.0+linux-x86_64
; estimated printing time (normal mode) = 2m 15s
; filament used [mm] = 80.00
; filament used [cm3] = 0.19
; filament used [g] = 0.24

G90
M83
G28
M104 S210
M190 S60
G92 E0

;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;TYPE:External perimeter
G1 Z0.2 F600
G1 X10 Y0 E0.5 F1200
G1 X10 Y10 E0.5 F1200
G1 X0 Y10 E0.5 F1200
G1 X0 Y0 E0.5 F1200
;TYPE:Perimeter
G1 X1 Y1 E0.4 F1500
G1 X9 Y1 E0.4 F1500
G1 X9 Y9 E0.4 F1500
G1 X1 Y9 E0.4 F1500
;TYPE:Solid infill
G1 X2 Y2 E0.3 F1800
G1 X8 Y2 E0.3 F1800
G1 X8 Y8 E0.3 F1800
G1 X2 Y8 E0.3 F1800

G1 E-0.8 F2400
G0 X0 Y0 F9000

;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;TYPE:External perimeter
G1 Z0.4 F600
G1 X10 Y0 E0.5 F1200
G1 X10 Y10 E0.5 F1200
G1 X0 Y10 E0.5 F1200
G1 X0 Y0 E0.5 F1200

G1 E-0.8 F2400
M84
"#
    )
}

/// Generate a Slicecore-style G-code with `; TYPE:` format matching gcode_gen.rs output.
fn synthetic_gcode_slicecore_style() -> String {
    format!(
        r#"; Generated by slicecore v0.1.0
; Marlin dialect

G90
M83
G28
M104 S200
M190 S60
G92 E0

; TYPE:Outer perimeter
G1 Z0.2 F600
G1 X10 Y0 E0.5 F1200
G1 X10 Y10 E0.5 F1200
G1 X0 Y10 E0.5 F1200
G1 X0 Y0 E0.5 F1200

G1 E-0.8 F2400
M84
"#
    )
}

// =============================================================================
// SC-1: G-code parser extracts layer boundaries, move counts, travel/extrusion
//       distances, and total filament per layer
// =============================================================================

#[test]
fn sc1_layer_boundaries_and_metrics() {
    let gcode = synthetic_gcode_bambu_style();
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "test.gcode", 1.75, 1.24);

    // Layer count: the parser may detect additional layers from both annotation-based
    // CHANGE_LAYER markers and Z-height changes in G1 moves, so we check >= 2
    assert!(
        analysis.layers.len() >= 2,
        "Should detect at least 2 layers, got {}",
        analysis.layers.len()
    );

    // Find layers at expected Z heights
    let z02_layer = analysis.layers.iter().find(|l| (l.z_height - 0.2).abs() < 0.01);
    let z04_layer = analysis.layers.iter().find(|l| (l.z_height - 0.4).abs() < 0.01);
    assert!(z02_layer.is_some(), "Should have a layer at Z=0.2");
    assert!(z04_layer.is_some(), "Should have a layer at Z=0.4");

    // Move counts > 0 for layers with content
    let z02 = z02_layer.unwrap();
    let z04 = z04_layer.unwrap();
    assert!(z02.move_count > 0, "Layer at Z=0.2 should have moves");
    assert!(z04.move_count > 0, "Layer at Z=0.4 should have moves");

    // Extrusion distance > 0 for layers with content
    assert!(
        z02.extrusion_distance_mm > 0.0,
        "Layer at Z=0.2 should have extrusion distance"
    );
    assert!(
        z04.extrusion_distance_mm > 0.0,
        "Layer at Z=0.4 should have extrusion distance"
    );

    // Total moves > 0
    assert!(analysis.total_moves > 0, "Should have total moves");

    // Total filament > 0
    assert!(
        analysis.total_filament_mm > 0.0,
        "Should have total filament"
    );
}

#[test]
fn sc1_per_layer_travel_distance() {
    let gcode = synthetic_gcode_bambu_style();
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "test.gcode", 1.75, 1.24);

    // Total travel should be > 0 (we have G0 moves)
    assert!(
        analysis.total_travel_mm > 0.0,
        "Should have travel distance from G0 moves"
    );

    // Total extrusion should be > 0
    assert!(
        analysis.total_extrusion_mm > 0.0,
        "Should have extrusion distance"
    );
}

// =============================================================================
// SC-2: Feature type annotations parsed and per-feature metrics accumulated
// =============================================================================

#[test]
fn sc2_feature_annotations_bambu() {
    let gcode = synthetic_gcode_bambu_style();
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "test.gcode", 1.75, 1.24);

    // BambuStudio uses "Outer wall", "Sparse infill", "Inner wall"
    assert!(
        analysis.features.contains_key("Outer wall"),
        "Should have Outer wall feature, got: {:?}",
        analysis.features.keys().collect::<Vec<_>>()
    );
    assert!(
        analysis.features.contains_key("Sparse infill"),
        "Should have Sparse infill feature"
    );
    assert!(
        analysis.features.contains_key("Inner wall"),
        "Should have Inner wall feature"
    );

    // Each feature should have non-zero metrics
    let outer = analysis.features.get("Outer wall").unwrap();
    assert!(
        outer.extrusion_e_mm > 0.0,
        "Outer wall should have extrusion"
    );
    assert!(outer.move_count > 0, "Outer wall should have moves");
}

#[test]
fn sc2_feature_annotations_prusaslicer() {
    let gcode = synthetic_gcode_prusaslicer_style();
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "test.gcode", 1.75, 1.24);

    assert!(
        analysis.features.contains_key("External perimeter")
            || analysis.features.contains_key("Perimeter"),
        "Should have perimeter feature from PrusaSlicer ;TYPE: format, got: {:?}",
        analysis.features.keys().collect::<Vec<_>>()
    );
}

#[test]
fn sc2_feature_annotations_slicecore() {
    let gcode = synthetic_gcode_slicecore_style();
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "test.gcode", 1.75, 1.24);

    assert!(
        analysis.features.contains_key("Outer perimeter"),
        "Should have Outer perimeter feature from Slicecore ; TYPE: format, got: {:?}",
        analysis.features.keys().collect::<Vec<_>>()
    );
}

// =============================================================================
// SC-3: Retraction count/distance, z-hop count/distance, and speed distribution
// =============================================================================

#[test]
fn sc3_retraction_and_speed_stats() {
    let gcode = synthetic_gcode_bambu_style();
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "test.gcode", 1.75, 1.24);

    // Retraction count (we have 2 retractions in synthetic gcode)
    assert!(
        analysis.retraction_count >= 2,
        "Should detect retractions (negative E), got: {}",
        analysis.retraction_count
    );
    assert!(
        analysis.retraction_distance_mm > 0.0,
        "Retraction distance should be positive"
    );

    // Speed statistics should have data
    let outer = analysis.features.get("Outer wall").unwrap();
    assert!(
        outer.speed_stats.min_mm_s > 0.0,
        "Should have speed data, min={}",
        outer.speed_stats.min_mm_s
    );
    assert!(
        outer.speed_stats.max_mm_s >= outer.speed_stats.min_mm_s,
        "Max >= min: max={} min={}",
        outer.speed_stats.max_mm_s,
        outer.speed_stats.min_mm_s
    );
    assert!(
        outer.speed_stats.mean_mm_s > 0.0,
        "Mean speed should be positive"
    );
}

#[test]
fn sc3_speed_distribution_multiple_features() {
    let gcode = synthetic_gcode_bambu_style();
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "test.gcode", 1.75, 1.24);

    // Different features should potentially have different speeds
    let outer = analysis.features.get("Outer wall").unwrap();
    let infill = analysis.features.get("Sparse infill").unwrap();

    // Outer wall at F1200 = 20mm/s, Sparse infill at F1800 = 30mm/s
    assert!(
        (outer.speed_stats.mean_mm_s - 20.0).abs() < 1.0,
        "Outer wall speed should be ~20mm/s, got {}",
        outer.speed_stats.mean_mm_s
    );
    assert!(
        (infill.speed_stats.mean_mm_s - 30.0).abs() < 1.0,
        "Sparse infill speed should be ~30mm/s, got {}",
        infill.speed_stats.mean_mm_s
    );
}

// =============================================================================
// SC-4: Header metadata parsed
// =============================================================================

#[test]
fn sc4_header_metadata_bambu() {
    let gcode = synthetic_gcode_bambu_style();
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "test.gcode", 1.75, 1.24);

    assert_eq!(analysis.slicer, slicecore_engine::SlicerType::BambuStudio);
    assert!(
        analysis.header.slicer_name.is_some(),
        "Should extract slicer name"
    );
    assert!(
        analysis.header.estimated_time_s.is_some(),
        "Should extract estimated time"
    );
    assert!(
        analysis.header.filament_length_mm.is_some(),
        "Should extract filament length"
    );
    assert!(
        analysis.header.layer_count.is_some(),
        "Should extract layer count"
    );
    assert_eq!(analysis.header.layer_count.unwrap(), 2);

    // Estimated time: 1m 30s = 90s
    assert!(
        (analysis.header.estimated_time_s.unwrap() - 90.0).abs() < 1.0,
        "Estimated time should be ~90s, got {}",
        analysis.header.estimated_time_s.unwrap()
    );

    // Filament length
    assert!(
        (analysis.header.filament_length_mm.unwrap() - 100.0).abs() < 0.01,
        "Filament length should be 100mm"
    );
}

#[test]
fn sc4_header_metadata_prusaslicer() {
    let gcode = synthetic_gcode_prusaslicer_style();
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "test.gcode", 1.75, 1.24);

    assert_eq!(analysis.slicer, slicecore_engine::SlicerType::PrusaSlicer);
    assert!(analysis.header.slicer_name.is_some());
    assert_eq!(
        analysis.header.slicer_name.as_deref(),
        Some("PrusaSlicer")
    );

    // Estimated time: 2m 15s = 135s
    assert!(
        analysis.header.estimated_time_s.is_some(),
        "Should extract estimated time"
    );
    assert!(
        (analysis.header.estimated_time_s.unwrap() - 135.0).abs() < 1.0,
        "Estimated time should be ~135s, got {}",
        analysis.header.estimated_time_s.unwrap()
    );

    // Filament length
    assert!(
        analysis.header.filament_length_mm.is_some(),
        "Should extract filament length"
    );
    assert!(
        (analysis.header.filament_length_mm.unwrap() - 80.0).abs() < 0.01,
        "Filament length should be 80mm"
    );
}

// =============================================================================
// SC-5: CLI analyze-gcode subcommand (verified by build success in Plan 02,
//       here test JSON output serialization)
// =============================================================================

#[test]
fn sc5_analysis_json_serializable() {
    let gcode = synthetic_gcode_bambu_style();
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "test.gcode", 1.75, 1.24);

    // Verify JSON serialization works
    let json = serde_json::to_string_pretty(&analysis).unwrap();
    assert!(
        json.contains("Outer wall"),
        "JSON should contain feature names"
    );
    assert!(
        json.contains("BambuStudio"),
        "JSON should contain slicer type"
    );

    // Verify deserialization round-trip
    let deserialized: slicecore_engine::GcodeAnalysis = serde_json::from_str(&json).unwrap();
    assert_eq!(deserialized.filename, "test.gcode");
    assert_eq!(deserialized.slicer, slicecore_engine::SlicerType::BambuStudio);
    assert_eq!(deserialized.layers.len(), analysis.layers.len());
    assert!(
        (deserialized.total_filament_mm - analysis.total_filament_mm).abs() < 0.001,
        "Round-trip filament should match"
    );
}

// =============================================================================
// SC-6: compare-gcode with delta computation
// =============================================================================

#[test]
fn sc6_comparison_deltas() {
    let gcode1 = synthetic_gcode_bambu_style();
    let gcode2 = synthetic_gcode_prusaslicer_style();

    let reader1 = std::io::BufReader::new(gcode1.as_bytes());
    let analysis1 = slicecore_engine::parse_gcode_file(reader1, "bambu.gcode", 1.75, 1.24);

    let reader2 = std::io::BufReader::new(gcode2.as_bytes());
    let analysis2 = slicecore_engine::parse_gcode_file(reader2, "prusa.gcode", 1.75, 1.24);

    let result = slicecore_engine::compare_gcode_analyses(analysis1, vec![analysis2]);

    assert_eq!(
        result.deltas.len(),
        1,
        "Should have one delta (for non-baseline file)"
    );
    assert_eq!(result.deltas[0].filename, "prusa.gcode");

    // Delta fields should be computed (can be positive or negative)
    // Just verify the fields exist and are finite
    assert!(
        result.deltas[0].total_time_delta_s.is_finite(),
        "Time delta should be finite"
    );
    assert!(
        result.deltas[0].filament_delta_mm.is_finite(),
        "Filament delta should be finite"
    );
    // layer_count_delta is i64 so always finite
    let _ = result.deltas[0].layer_count_delta;

    // Comparison JSON serializable
    let json = serde_json::to_string_pretty(&result).unwrap();
    assert!(json.contains("deltas"), "JSON should contain deltas key");
    assert!(
        json.contains("prusa.gcode"),
        "JSON should contain compared filename"
    );
}

#[test]
fn sc6_comparison_same_file() {
    let gcode = synthetic_gcode_bambu_style();

    let reader1 = std::io::BufReader::new(gcode.as_bytes());
    let analysis1 = slicecore_engine::parse_gcode_file(reader1, "file1.gcode", 1.75, 1.24);

    let reader2 = std::io::BufReader::new(gcode.as_bytes());
    let analysis2 = slicecore_engine::parse_gcode_file(reader2, "file2.gcode", 1.75, 1.24);

    let result = slicecore_engine::compare_gcode_analyses(analysis1, vec![analysis2]);

    // Comparing same content should yield zero deltas
    assert!(
        result.deltas[0].total_time_delta_s.abs() < 0.01,
        "Same content should have ~0 time delta"
    );
    assert!(
        result.deltas[0].filament_delta_mm.abs() < 0.01,
        "Same content should have ~0 filament delta"
    );
    assert_eq!(result.deltas[0].layer_count_delta, 0);
}

// =============================================================================
// SC-7: Real BambuStudio G-code validation (gated with #[ignore] for CI)
// =============================================================================

#[test]
#[ignore] // Requires real G-code files in tmp/gcode-bambu/
fn sc7_real_bambustudio_gcode() {
    let path = std::path::Path::new("tmp/gcode-bambu/Cube_PLA.gcode");
    if !path.exists() {
        eprintln!("Skipping: real G-code file not found at {:?}", path);
        return;
    }

    let file = std::fs::File::open(path).unwrap();
    let reader = std::io::BufReader::new(file);
    let analysis = slicecore_engine::parse_gcode_file(reader, "Cube_PLA.gcode", 1.75, 1.24);

    // Should detect BambuStudio
    assert_eq!(analysis.slicer, slicecore_engine::SlicerType::BambuStudio);

    // Should have layers
    assert!(
        analysis.layers.len() > 10,
        "Real cube should have >10 layers, got {}",
        analysis.layers.len()
    );

    // Should have header metadata
    assert!(
        analysis.header.estimated_time_s.is_some(),
        "Should extract time estimate from header"
    );
    assert!(
        analysis.header.filament_length_mm.is_some(),
        "Should extract filament from header"
    );

    // Computed filament should be within reasonable range of header-reported value
    if let Some(header_filament) = analysis.header.filament_length_mm {
        let ratio = analysis.total_filament_mm / header_filament;
        assert!(
            ratio > 0.5 && ratio < 2.0,
            "Computed filament ({:.1}mm) should be within 50-200% of header ({:.1}mm), ratio: {:.2}",
            analysis.total_filament_mm,
            header_filament,
            ratio
        );
    }

    // Should have features
    assert!(
        !analysis.features.is_empty(),
        "Should detect feature annotations"
    );

    // Should have retractions
    assert!(
        analysis.retraction_count > 0,
        "Real print should have retractions"
    );

    println!("Real BambuStudio analysis:");
    println!("  Layers: {}", analysis.layers.len());
    println!(
        "  Total time (computed): {:.1}s",
        analysis.total_time_estimate_s
    );
    println!(
        "  Total time (header): {:?}",
        analysis.header.estimated_time_s
    );
    println!(
        "  Filament (computed): {:.1}mm",
        analysis.total_filament_mm
    );
    println!(
        "  Filament (header): {:?}",
        analysis.header.filament_length_mm
    );
    println!(
        "  Features: {:?}",
        analysis.features.keys().collect::<Vec<_>>()
    );
    println!("  Retractions: {}", analysis.retraction_count);
}

#[test]
#[ignore] // Requires real G-code files in tmp/gcode-bambu/
fn sc7_real_comparison_two_files() {
    let path1 = std::path::Path::new("tmp/gcode-bambu/Cube_PLA.gcode");
    let path2 = std::path::Path::new("tmp/gcode-bambu/3DBenchy_PLA.gcode");
    if !path1.exists() || !path2.exists() {
        eprintln!("Skipping: real G-code files not found");
        return;
    }

    let analysis1 = slicecore_engine::parse_gcode_file(
        std::io::BufReader::new(std::fs::File::open(path1).unwrap()),
        "Cube_PLA.gcode",
        1.75,
        1.24,
    );
    let analysis2 = slicecore_engine::parse_gcode_file(
        std::io::BufReader::new(std::fs::File::open(path2).unwrap()),
        "3DBenchy_PLA.gcode",
        1.75,
        1.24,
    );

    let result = slicecore_engine::compare_gcode_analyses(analysis1, vec![analysis2]);

    // Benchy should have more layers, more filament, more time than a cube
    assert!(
        result.deltas[0].layer_count_delta > 0,
        "Benchy should have more layers than cube"
    );
    assert!(
        result.deltas[0].filament_delta_mm > 0.0,
        "Benchy should use more filament"
    );

    println!("Comparison: Cube vs Benchy");
    println!("  Layer delta: {}", result.deltas[0].layer_count_delta);
    println!(
        "  Filament delta: {:.1}mm",
        result.deltas[0].filament_delta_mm
    );
    println!(
        "  Time delta: {:.1}s",
        result.deltas[0].total_time_delta_s
    );
}

// =============================================================================
// Edge case tests
// =============================================================================

#[test]
fn edge_case_empty_gcode() {
    let gcode = "";
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "empty.gcode", 1.75, 1.24);
    assert_eq!(analysis.layers.len(), 0);
    assert_eq!(analysis.total_moves, 0);
    assert_eq!(analysis.total_filament_mm, 0.0);
    assert_eq!(analysis.slicer, slicecore_engine::SlicerType::Unknown);
}

#[test]
fn edge_case_comments_only() {
    let gcode = "; This is a comment\n; Another comment\n";
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "comments.gcode", 1.75, 1.24);
    assert_eq!(analysis.layers.len(), 0);
    assert_eq!(analysis.total_moves, 0);
    assert_eq!(analysis.slicer, slicecore_engine::SlicerType::Unknown);
}

#[test]
fn edge_case_m82_absolute_extrusion() {
    // Test absolute extrusion mode tracking
    let gcode =
        "G90\nM82\nG1 Z0.2 F600\nG1 X10 Y0 E1.0 F1200\nG1 X20 Y0 E2.0 F1200\nG92 E0\nG1 X30 Y0 E1.0 F1200\n";
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "m82.gcode", 1.75, 1.24);

    // Total filament should be ~3mm (1.0 + 1.0 + 1.0 after G92 reset)
    assert!(
        (analysis.total_filament_mm - 3.0).abs() < 0.1,
        "M82 absolute extrusion: expected ~3.0mm, got {:.2}mm",
        analysis.total_filament_mm
    );
}

#[test]
fn edge_case_slicecore_gcode_detection() {
    let gcode =
        "; Generated by slicecore v0.1.0\nG90\nM83\nG1 Z0.2 F600\n; TYPE:Outer perimeter\nG1 X10 Y0 E0.5 F1200\n";
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "slicecore.gcode", 1.75, 1.24);
    assert_eq!(analysis.slicer, slicecore_engine::SlicerType::Slicecore);
}

#[test]
fn edge_case_g92_reset_in_absolute_mode() {
    // Verify G92 E0 reset properly resets the E-axis reference point in absolute mode
    let gcode = "M82\nG1 X10 Y0 E5.0 F3000\nG92 E0\nG1 X20 Y0 E3.0 F3000\n";
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "reset.gcode", 1.75, 1.24);

    // First move: E 0->5.0 = 5.0mm, G92 E0 resets, second move: E 0->3.0 = 3.0mm
    // Total = 8.0mm
    assert!(
        (analysis.total_filament_mm - 8.0).abs() < 0.1,
        "G92 E0 reset: expected ~8.0mm, got {:.2}mm",
        analysis.total_filament_mm
    );
}

#[test]
fn edge_case_filament_volume_and_weight() {
    let gcode = synthetic_gcode_bambu_style();
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "test.gcode", 1.75, 1.24);

    // Volume and weight should be computed from filament length
    assert!(
        analysis.total_filament_volume_mm3 > 0.0,
        "Should have filament volume"
    );
    assert!(
        analysis.total_filament_weight_g > 0.0,
        "Should have filament weight"
    );

    // Cross-check with standalone functions
    let expected_volume =
        slicecore_engine::filament_mm_to_volume_mm3(analysis.total_filament_mm, 1.75);
    let expected_weight =
        slicecore_engine::filament_mm_to_weight_g(analysis.total_filament_mm, 1.75, 1.24);
    assert!(
        (analysis.total_filament_volume_mm3 - expected_volume).abs() < 0.01,
        "Volume should match standalone function"
    );
    assert!(
        (analysis.total_filament_weight_g - expected_weight).abs() < 0.001,
        "Weight should match standalone function"
    );
}

#[test]
fn edge_case_multiple_slicer_comparison() {
    // Compare BambuStudio, PrusaSlicer, and Slicecore outputs
    let gcode1 = synthetic_gcode_bambu_style();
    let gcode2 = synthetic_gcode_prusaslicer_style();
    let gcode3 = synthetic_gcode_slicecore_style();

    let a1 = slicecore_engine::parse_gcode_file(
        std::io::BufReader::new(gcode1.as_bytes()),
        "bambu.gcode",
        1.75,
        1.24,
    );
    let a2 = slicecore_engine::parse_gcode_file(
        std::io::BufReader::new(gcode2.as_bytes()),
        "prusa.gcode",
        1.75,
        1.24,
    );
    let a3 = slicecore_engine::parse_gcode_file(
        std::io::BufReader::new(gcode3.as_bytes()),
        "slicecore.gcode",
        1.75,
        1.24,
    );

    let result = slicecore_engine::compare_gcode_analyses(a1, vec![a2, a3]);

    assert_eq!(
        result.deltas.len(),
        2,
        "Should have 2 deltas (prusa + slicecore)"
    );
    assert_eq!(result.deltas[0].filename, "prusa.gcode");
    assert_eq!(result.deltas[1].filename, "slicecore.gcode");

    // All deltas should have finite values
    for delta in &result.deltas {
        assert!(delta.total_time_delta_s.is_finite());
        assert!(delta.filament_delta_mm.is_finite());
    }
}

#[test]
fn edge_case_time_estimate_consistency() {
    let gcode = synthetic_gcode_bambu_style();
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "test.gcode", 1.75, 1.24);

    // Total computed time should be the sum of per-layer times
    let layer_time_sum: f64 = analysis
        .layers
        .iter()
        .map(|l| l.layer_time_estimate_s)
        .sum();
    assert!(
        (analysis.total_time_estimate_s - layer_time_sum).abs() < 0.01,
        "Total time ({:.3}s) should equal sum of layer times ({:.3}s)",
        analysis.total_time_estimate_s,
        layer_time_sum
    );
}

#[test]
fn edge_case_line_count() {
    let gcode = synthetic_gcode_bambu_style();
    let reader = std::io::BufReader::new(gcode.as_bytes());
    let analysis = slicecore_engine::parse_gcode_file(reader, "test.gcode", 1.75, 1.24);

    // Line count should be > 0 for non-empty file
    assert!(
        analysis.line_count > 0,
        "Should count lines in the file"
    );
}
