//! Shared calibration CLI utilities.
//!
//! Helper functions used by all calibration subcommands: profile resolution,
//! instruction file generation, and G-code header formatting.
//!
//! These functions are scaffolded now and will be called by calibration
//! subcommand implementations in subsequent plans.

use std::path::{Path, PathBuf};

use slicecore_engine::config::PrintConfig;
use slicecore_engine::profile_resolve::ProfileResolver;

/// Resolves calibration profile flags into a merged `PrintConfig`.
///
/// If no profile flags are specified, returns `PrintConfig::default()`.
///
/// # Errors
///
/// Returns an error if profile resolution or merging fails.
pub fn resolve_calibration_config(
    machine: &Option<String>,
    filament: &Option<String>,
    process: &Option<String>,
    profiles_dir: &Option<PathBuf>,
) -> Result<PrintConfig, Box<dyn std::error::Error>> {
    // If no profiles specified, return defaults
    if machine.is_none() && filament.is_none() && process.is_none() {
        return Ok(PrintConfig::default());
    }

    let resolver = ProfileResolver::new(profiles_dir.as_deref().map(Path::new));

    let mut config = PrintConfig::default();

    if let Some(ref m) = machine {
        let resolved = resolver.resolve(m, "machine")?;
        let toml_str = std::fs::read_to_string(&resolved.path)?;
        let partial: PrintConfig = toml::from_str(&toml_str)?;
        config.machine = partial.machine;
    }

    if let Some(ref f) = filament {
        let resolved = resolver.resolve(f, "filament")?;
        let toml_str = std::fs::read_to_string(&resolved.path)?;
        let partial: PrintConfig = toml::from_str(&toml_str)?;
        config.filament = partial.filament;
    }

    if let Some(ref p) = process {
        let resolved = resolver.resolve(p, "process")?;
        let toml_str = std::fs::read_to_string(&resolved.path)?;
        let partial: PrintConfig = toml::from_str(&toml_str)?;
        // Merge process fields
        config.layer_height = partial.layer_height;
        config.extrusion_multiplier = partial.extrusion_multiplier;
    }

    Ok(config)
}

/// Writes a markdown instruction file for a calibration test.
///
/// # Errors
///
/// Returns an error if the file cannot be written.
pub fn write_instructions(
    path: &Path,
    title: &str,
    sections: &[(String, String)],
) -> Result<(), std::io::Error> {
    use std::io::Write;
    let mut file = std::fs::File::create(path)?;
    writeln!(file, "# {title}")?;
    writeln!(file)?;
    writeln!(
        file,
        "Generated: {}",
        chrono_lite_date()
    )?;
    writeln!(file)?;
    for (heading, content) in sections {
        writeln!(file, "## {heading}")?;
        writeln!(file)?;
        writeln!(file, "{content}")?;
        writeln!(file)?;
    }
    Ok(())
}

/// Formats a G-code header comment block for calibration prints.
///
/// Includes SliceCore version and calibration-specific parameters.
#[must_use]
pub fn format_calibration_header(test_name: &str, params: &[(&str, String)]) -> String {
    let mut lines = Vec::new();
    lines.push(format!("; SliceCore Calibration: {test_name}"));
    lines.push(format!(
        "; Generated by SliceCore v{}",
        env!("CARGO_PKG_VERSION")
    ));
    for (key, value) in params {
        lines.push(format!("; {key}: {value}"));
    }
    lines.push(String::new());
    lines.join("\n")
}

/// Returns current date as a simple string without pulling in chrono.
fn chrono_lite_date() -> String {
    // Use a simple approach -- just return a placeholder since we don't
    // want to add a chrono dependency for this.
    "see file timestamp".to_string()
}
